# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'InfiniteScroll_Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'MWInfiniteScroll', :path => '../'

  # Pods for InfiniteScroll_Example

end
